name: Sagemaker Deploy Pipeline

on:
  push:
    branches:
      - main

env:
  SAGEMAKER_PROJECT_NAME: githubProj
  SAGEMAKER_PROJECT_NAME_ID: p-1succyhht0ye
  SAGEMAKER_PIPELINE_ROLE_ARN: arn:aws:iam::058264373029:role/service-role/AmazonSageMakerServiceCatalogProductsExecutionRole
  SOURCE_MODEL_PACKAGE_GROUP_NAME: p-1succyhht0ye
  MODEL_EXECUTION_ROLE_ARN: arn:aws:iam::058264373029:role/service-role/AmazonSageMakerServiceCatalogProductsExecutionRole
  AWS_REGION: us-east-1
  ARTIFACT_BUCKET: sagemaker-project-p-98gc52dh9vwy
  EXPORT_TEMPLATE_NAME: template-export.yml
  EXPORT_TEMPLATE_STAGING_CONFIG: staging-config-export.json
  EXPORT_TEMPLATE_STAGING_PARAMS: staging-params-export.json
  EXPORT_TEMPLATE_STAGING_TAGS: staging-tags-export.json
  EXPORT_TEMPLATE_PROD_PARAMS: prod-params-export.json
  EXPORT_TEMPLATE_PROD_TAGS: prod-tags-export.json
  EXPORT_TEST_RESULTS: test-results.json

jobs:
  SagemakerModelDeploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Sagemaker Deploy CheckOut
        uses: actions/checkout@v4
        with:
          repository: DevOps-ManiInspire/sagemaker-model-build # Replace with the owner/repository name
          fetch-depth: 0 # Fetch all history for proper sparse checkout
          sparse-checkout-cone-mode: true # Recommended for better performance
      - name: Build and Install
        run: |
          mkdir /opt/Recommender-Live-Deploy
          mv ./ModelBuild-GitHubPipeline/deploy/* /opt/Recommender-Live-Deploy
          pip3 install --upgrade --force-reinstall "botocore>1.21.30" "boto3>1.18.30" "awscli>1.20.30"
          ls -lrt $HOME/.local/
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }} # Replace with your AWS Region
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Add in repository secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Add in repository secrets
          
      - name: Verify AWS Configuration
        run: aws sts get-caller-identity

      - name: Build Model with SageMaker
        run: |
          cd /opt/Recommender-Live-Deploy
          python3 build.py --model-execution-role "${{ env.MODEL_EXECUTION_ROLE_ARN }}" \
                     --model-package-group-name "${{ env.SOURCE_MODEL_PACKAGE_GROUP_NAME }}" \
                     --sagemaker-project-id "${{ env.SAGEMAKER_PROJECT_ID }}" \
                     --sagemaker-project-name "${{ env.SAGEMAKER_PROJECT_NAME }}" \
                     --s3-bucket "${{ env.ARTIFACT_BUCKET }}" \
                     --export-cfn-params-tags "True"

      - name: Package CloudFormation Template
        run: |
          cd /opt/Recommender-Live-Deploy
          export PATH="$HOME/.local/bin:$PATH"
          aws cloudformation package --template endpoint-config-template.yml \
                                     --s3-bucket "${{ env.ARTIFACT_BUCKET }}" \
                                     --output-template "${{ env.EXPORT_TEMPLATE_NAME }}"
          cat $EXPORT_TEMPLATE_STAGING_CONFIG
          cat $EXPORT_TEMPLATE_PROD_CONFIG
          ls -lrt /opt/Recommender-Live-Deploy

      - name: Deploy Staging Cloudformation 
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: sagemaker-${{ env.SAGEMAKER_PROJECT_NAME }}-${{ env.SAGEMAKER_PROJECT_NAME_ID }}-deploy-staging
          template: /opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_NAME }}
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            file:///opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_STAGING_PARAMS }}
          tags: |
            file:///opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_STAGING_TAGS }}
          no-fail-on-empty-changeset: '1'
          timeout-in-minutes: 30

      - name: Testing Sagemaker Build
        run: |
          cd /opt/Recommender-Live-Deploy
          ls -lrt
          python3 test/test.py \
              --import-build-config /opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_STAGING_CONFIG }} \
              --export-test-results /opt/Recommender-Live-Deploy/${{ env.EXPORT_TEST_RESULTS }}
          cat /opt/Recommender-Live-Deploy/${{ env.EXPORT_TEST_RESULTS }}

      - name: Deploy Production Cloudformation 
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
            name: sagemaker-${{ env.SAGEMAKER_PROJECT_NAME }}-${{ env.SAGEMAKER_PROJECT_NAME_ID }}-prod-staging
            template: /opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_NAME }}
            capabilities: CAPABILITY_NAMED_IAM
            parameter-overrides: |
                file:///opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_PROD_PARAMS }}
            tags: |
                file:///opt/Recommender-Live-Deploy/${{ env.EXPORT_TEMPLATE_PROD_TAGS }}
            no-fail-on-empty-changeset: '1'
            timeout-in-minutes: 30